### ISSUE TITLE
Returning special matrix types wrapping the sparse matrices is a bit painful.

### ISSUE THREAD

**Issue by jakebolewski** [JuliaSparse/MatrixMarket.jl#9]
Special matrix types (`Symmetric`, `Hermitian`) assume that the underlying matrix is dense.  You can't do very much with the resulting matrix when it is wrapped this way.  I feel it would be better to just return the full sparse matrix.

cc @jiahao

**Comment by jiahao** [comment]
Yeah, I wondered if we should do that. Note that MatrixMarket allows specifying skew symmetry (`A' == -A`) but since Julia doesn't have this type I made a copy of the transposed elements to read out matrices with this symmetry. So there's already precedent in this package for duplicating symmetric elements.

**Comment by jakebolewski** [comment]
I removed them.
